[application]

[web.app]

# HTML title tag content
title = "dxrc"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

# Bundle configuration for cross-platform desktop apps
[bundle]
identifier = "com.deckyfx.dxrc"
publisher = "DeckyFX"
icon = ["assets/icon.png", "assets/icon.ico", "assets/icon.icns"]

# macOS specific configuration
[bundle.macos]
minimum_system_version = "10.15"
category = "DeveloperTool"