name: Build macOS

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create GitHub release after build?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Install Dioxus CLI
        run: |
          chmod +x install-dx-rc.sh
          ./install-dx-rc.sh v0.7.0-rc.3

      - name: Add Dioxus to PATH
        run: echo "$HOME/.dx/bin" >> $GITHUB_PATH

      - name: Resolve and build dependencies
        run: cargo build --release --target x86_64-apple-darwin

      - name: Build desktop bundle
        run: dx bundle --macos --release --package-types="macos" --out-dir="dist"

      - name: Compress macOS app bundle
        run: |
          cp README-MACOS.txt dist/README.txt
          cd dist
          zip -r Dxrc.app.zip Dxrc.app README.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dxrc-macos
          path: dist/*.zip
          if-no-files-found: warn
