name: Build Windows

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create GitHub release after build?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Install Dioxus CLI
        shell: pwsh
        run: .\install-dx-rc.ps1 v0.7.0-rc.3

      - name: Add Dioxus to PATH
        shell: pwsh
        run: echo "$env:USERPROFILE\.dx\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Resolve and build dependencies
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Build desktop bundle
        run: dx bundle --windows --release --package-types="nsis" --out-dir="dist"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dxrc-windows
          path: dist/*.exe
          if-no-files-found: warn
